### ISSUE TITLE
code components are incompatible with codegen

### ISSUE THREAD

**Issue by igorovic** [plasmicapp/code-components#6]
Hi,

I tried to use a code component with codegen and the generated code for the page has an empty import path.

```ts
import { CompdeYtwwol3M } from ""; // plasmic-import: deYtwwol3m/codeComponent
```

I am wondering if `code components` should NOT be used with codegen ?

**Comment by yang** [comment]
Hi @igorovic , you will need to specify the import paths in the register component call. See docs at https://docs.plasmic.app/learn/registering-code-components/#scheme=codegen. Let me know if that helps.

**Comment by igorovic** [comment]
Hi Yan,

Thanks for the quick response it works with the `importPath`.
